// <auto-generated />
using MealMind.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealMind.Api.Migrations
{
    [DbContext(typeof(MealMindDBContext))]
    [Migration("20260713134830_AddNutritionInfo")]
    partial class AddNutritionInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MealMind.Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealMind.Api.Models.Recipe", b =>
                {
                    b.OwnsOne("MealMind.Api.Models.NutritionInfo", "NutritionInfo", b1 =>
                        {
                            b1.Property<int>("RecipeId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Calories")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("CarbsGrams")
                                .HasColumnType("REAL");

                            b1.Property<double>("FatGrams")
                                .HasColumnType("REAL");

                            b1.Property<double>("ProteinGrams")
                                .HasColumnType("REAL");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("NutritionInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
